# Dungeon Maze worlds
worlds: []
preloadWorlds: []

# World mangement
unloadWorldsOnPluginDisable: true

# Gameplay settings
allowSurface: true
worldProtection: false
blockWhiteList: []

# Update checker
enableUpdateCheckerOnStartup: true

# Permission Support
usePermissions : true
useBypassPermissions : true

# Mob Spawner Populator
mobs:
- Blaze
- Creeper
- Enderman
- Ghast
- MagmaCube
- Pig
- PigZombie
- Silverfish
- Skeleton
- Spider
- Zombie